server:
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    accesslog:
      enabled: true
  port: 8080


spring:
  profiles:
    active: development
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false
  data:
    redis:
      port: 6379
      host: localhost
      password:
      timeout: 600ms
#      sentinel:
#        master: mymaster
#        nodes: localhost



